tf_from_uav_pose_ros2:
  ros__parameters:
    # Topic names
    poseTopicName: "/X3/odometry"
    rawPoseTopicName: "/unused/raw"
    stdPoseTopicName: "/unused/std"
    stdRawPoseTopicName: "/unused/std_raw"
    throttledPoseTopicName: "/unused/throttled"
    throttledUAVPoseTopicName: "/unused/throttled_uav"
    
    # Frame IDs
    machineFrameID: "machine_1"
    worldFrameID: "world"
    worldENUFrameID: "world_ENU"
    worldNWUFrameID: "world_NWU"
    cameraFrameID: "machine_1_camera_link"
    cameraRGBOpticalFrameID: "machine_1_camera_rgb_optical_link"
    
    # Control flags
    dontPublishTFs: false
    
    # Dynamic reconfigure equivalent parameters
    offsetX: 0.0
    offsetY: 0.0
    offsetZ: 0.0
    covarianceX: 0.0
    covarianceY: 0.0
    covarianceZ: 0.0
    throttleRate: 10.0
    
    # Camera static publishing configuration
    # Updated to match X3 drone model: camera at [0.2, 0.0, 0.0] with 30° downward tilt
    cameraStaticPublish:
      publish: true
      topic: "/machine_1/camera/pose"
      pose_optical_topic: "/machine_1/camera/pose_optical"
      # Corrected parameters for X3: [x, y, z, qx, qy, qz, qw]
      # Position: 0.2m forward from center, 30° downward tilt (rotation about Y;
      # quaternion = [0, sin(15°), 0, cos(15°)])
      TFParameters: [0.2, 0.0, 0.0, 0.0, 0.2588, 0.0, 0.9659]  # 30° pitch down keeps optical axis toward ground
