# Low-Level Controller Configuration for X3 Drone

waypoint_controller:
  ros__parameters:
    # Control parameters
    control_frequency: 50.0
    position_tolerance: 0.02      # meters
    velocity_tolerance: 0.05      # m/s
    waypoint_timeout: 1.0         # seconds before fail-safe hover engages

    # PID gains for position control (sharper response for search hold)
    kp_xy: 3.4                   # Proportional gain for X,Y
    ki_xy: 0.05                  # Integral gain for X,Y
    kd_xy: 0.55                  # Derivative gain for X,Y
    kp_z: 2.2                    # Proportional gain for Z
    ki_z: 0.08                   # Integral gain for Z
    kd_z: 0.8                    # Derivative gain for Z

    # Velocity limits
    max_velocity_xy: 4.0         # m/s for X,Y
    max_velocity_z: 2.5          # m/s for Z

attitude_controller:
  ros__parameters:
    # Control parameters
    control_frequency: 100.0     # Higher frequency for attitude
    attitude_tolerance: 0.05      # radians (约2.9°容差)

    # PID gains for attitude control
    kp_roll: 3.8                 # Proportional gain for roll
    ki_roll: 0.12                # Integral gain for roll
    kd_roll: 0.28                # Derivative gain for roll
    kp_pitch: 3.8                # Proportional gain for pitch
    ki_pitch: 0.12               # Integral gain for pitch
    kd_pitch: 0.28               # Derivative gain for pitch
    kp_yaw: 2.6                  # Proportional gain for yaw
    ki_yaw: 0.08                 # Integral gain for yaw
    kd_yaw: 0.1                  # Derivative gain for yaw

    # Angular velocity limits
    max_angular_velocity_roll: 2.3   # rad/s
    max_angular_velocity_pitch: 2.3  # rad/s
    max_angular_velocity_yaw: 1.2    # rad/s

velocity_controller:
  ros__parameters:
    # Control parameters
    control_frequency: 100.0
    velocity_smoothing: 0.2      # 0.0 = no smoothing, 1.0 = full smoothing

    # Velocity and angular velocity limits (final safety limits)
    max_linear_velocity_xy: 4.5  # m/s
    max_linear_velocity_z: 2.5   # m/s
    max_angular_velocity_xy: 2.3 # rad/s (roll/pitch rates)
    max_angular_velocity_z: 1.2  # rad/s (yaw rate)

    # Velocity PID gains (world frame)
    kp_vx: 0.55
    kp_vy: 0.55
    kp_vz: 0.7

    # Angular velocity proportional gains (body frame)
    kp_wx: 0.6
    kp_wy: 0.6
    kp_wz: 0.5
