# Low-Level Controller Configuration for X3 Drone

waypoint_controller:
  ros__parameters:
    # Control parameters
    control_frequency: 50.0
    position_tolerance: 0.05      # meters
    velocity_tolerance: 0.1      # m/s
    waypoint_timeout: 1.5         # seconds before fail-safe hover engages

    # PID gains for position control (smoother response to prevent oscillations)
    kp_xy: 1.2                   # Proportional gain for X,Y - reduced to prevent oscillations
    ki_xy: 0.02                  # Integral gain for X,Y - reduced to prevent wind-up
    kd_xy: 0.4                   # Derivative gain for X,Y - increased for better damping
    kp_z: 1.0                    # Proportional gain for Z - reduced for smoother altitude control
    ki_z: 0.03                   # Integral gain for Z
    kd_z: 0.5                    # Derivative gain for Z - reduced for smoother response

    # Velocity limits
    max_velocity_xy: 3.0         # m/s for X,Y
    max_velocity_z: 1.5          # m/s for Z

attitude_controller:
  ros__parameters:
    # Control parameters
    control_frequency: 100.0     # Higher frequency for attitude
    attitude_tolerance: 0.05      # radians (约2.9°容差)

    # PID gains for attitude control (reduced to prevent oscillations)
    kp_roll: 1.8                 # Proportional gain for roll - reduced for stability
    ki_roll: 0.05                # Integral gain for roll - reduced to prevent wind-up
    kd_roll: 0.3                # Derivative gain for roll - increased for better damping
    kp_pitch: 1.8                # Proportional gain for pitch - reduced for stability
    ki_pitch: 0.05               # Integral gain for pitch - reduced to prevent wind-up
    kd_pitch: 0.3               # Derivative gain for pitch - increased for better damping
    kp_yaw: 1.5                  # Proportional gain for yaw - reduced for smoother yaw control
    ki_yaw: 0.04                 # Integral gain for yaw - reduced
    kd_yaw: 0.2                  # Derivative gain for yaw - increased for better damping

    # Angular velocity limits
    max_angular_velocity_roll: 1.8   # rad/s
    max_angular_velocity_pitch: 1.8  # rad/s
    max_angular_velocity_yaw: 1.0    # rad/s

velocity_controller:
  ros__parameters:
    # Control parameters
    control_frequency: 100.0
    velocity_smoothing: 0.6      # 0.0 = no smoothing, 1.0 = full smoothing

    # Velocity and angular velocity limits (final safety limits)
    max_linear_velocity_xy: 3.2  # m/s
    max_linear_velocity_z: 1.6   # m/s
    max_angular_velocity_xy: 2.3 # rad/s (roll/pitch rates)
    max_angular_velocity_z: 1.2  # rad/s (yaw rate)

    # Velocity PID gains (world frame)
    kp_vx: 0.5
    kp_vy: 0.5
    kp_vz: 0.5

    # Angular velocity proportional gains (body frame)
    kp_wx: 0.45
    kp_wy: 0.45
    kp_wz: 0.4
